### ISSUE TITLE
Duplicated caption when converting to Word

### ISSUE THREAD

**Issue by pavelaegorov** [hughjonesd/huxtable#227]
As the output of the example code below, the Word shows duplicated caption for the generated table. 

Example 

library(huxtable)

jams <- hux(
  Type  = c("Strawberry", "Raspberry", "Plum"),
  Price = c(1.90, 2.10, 1.80)
)

library(dplyr) 

jams %>% 
  set_all_padding(4) %>% 
  set_outer_padding(0) %>% 
  set_number_format(2) %>% 
  set_bold(row = c(1), col = everywhere) %>% 
  set_bottom_border(row = 1, col = everywhere) %>% 
  set_width(0.4) %>% 
  set_caption("Pots of jam for sale") -> jams

quick_docx(jams, 
           file = "jams.docx",
           borders = 0.4,
           open = interactive()
)

**Comment by hughjonesd** [comment]
Thank you. Can reproduce.

**Comment by hughjonesd** [comment]
Could you see if it's fixed in master, using `remotes::install_github("hughjonesd/huxtable")`?

**Comment by pavelaegorov** [comment]
> remotes::install_github("hughjonesd/huxtable")

Sorry, doesn't work

**Comment by hughjonesd** [comment]
You mean the install command doesn't work? Or the bug is still present?

**Comment by pavelaegorov** [comment]
I mean the bug is still there

From: David Hugh-Jones ***@***.***>
Date: Saturday, 18 June 2022, 11:04
To: hughjonesd/huxtable ***@***.***>
Cc: pavelaegorov ***@***.***>, Author ***@***.***>
Subject: Re: [hughjonesd/huxtable] Duplicated caption when converting to Word (Issue #227)

You mean the install command doesn't work? Or the bug is still present?

**Comment by hughjonesd** [comment]
OK. Please could you confirm your flextable package version? Thanks.

**Comment by pavelaegorov** [comment]
> packageVersion("huxtable")
[1] ‘5.5.0.9000’



From: David Hugh-Jones ***@***.***>
Date: Saturday, 18 June 2022, 14:13
To: hughjonesd/huxtable ***@***.***>
Cc: pavelaegorov ***@***.***>, Author ***@***.***>
Subject: Re: [hughjonesd/huxtable] Duplicated caption when converting to Word (Issue #227)

OK. Please could you confirm your flextable package version? Thanks.

**Comment by hughjonesd** [comment]
Right, but what is your *flextable* package version?

**Comment by pavelaegorov** [comment]
> packageVersion("huxtable")
[1] ‘5.5.0.9000’
> packageVersion("flextable")
[1] ‘0.7.2’


From: David Hugh-Jones ***@***.***>
Date: Saturday, 18 June 2022, 16:19
To: hughjonesd/huxtable ***@***.***>
Cc: pavelaegorov ***@***.***>, Author ***@***.***>
Subject: Re: [hughjonesd/huxtable] Duplicated caption when converting to Word (Issue #227)

Right, but what is your flextable package version?

**Comment by hughjonesd** [comment]
Mm. OK, now I can't reproduce. With current github and flextable 0.7.2, your code just gives me a single caption.

**Comment by hughjonesd** [comment]
Could I maybe check the officer version?

**Comment by pavelaegorov** [comment]
Lucky you are! Maybe something wrong from my side)
By the way, thanks a LOT!! For your package, just calculated some clinical trial results and it was very easy to send tables to word with the huxtable!! Great job

Pavel

> packageVersion("huxtable")
[1] ‘5.5.0.9000’
> packageVersion("flextable")
[1] ‘0.7.2’
> packageVersion("officer")
[1] ‘0.4.3’



From: David Hugh-Jones ***@***.***>
Date: Saturday, 18 June 2022, 17:40
To: hughjonesd/huxtable ***@***.***>
Cc: pavelaegorov ***@***.***>, Author ***@***.***>
Subject: Re: [hughjonesd/huxtable] Duplicated caption when converting to Word (Issue #227)

Could I maybe check the officer version?

**Comment by hughjonesd** [comment]
Glad to hear it!

This is hard to debug, obviously. If you could try `debugonce(quick_docx)` and maybe `debugonce(huxtable:::as_flextable.huxtable)` and see what is going on, that might give some insight - in particular, do you see multiple calls to `set_caption()`? See `?debug` and `?browser` if you're not familiar with using the debugger.

**Comment by hughjonesd** [comment]
If possible, could you check whether you get the double caption when you evaluate a huxtable with a caption in an rmarkdown Word document?

**Comment by hughjonesd** [comment]
Closing until I hear anything back. My guess is that this might be due to confusing `huxtable::set_caption()` with `flextable::set_caption()`.
